### ISSUE TITLE
Error 500:  Unknown custom element: <lit-error-500>

### ISSUE THREAD

**Issue by ordago** [litstack/demo#2]
```
[Vue warn]: Unknown custom element: <lit-error-500> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

On this page: https://demo.litstack.io/admin/orders/create

![image](https://user-images.githubusercontent.com/6376814/112723563-2a2bf900-8f07-11eb-87df-48568f786503.png)

**Comment by cbl** [comment]
Thanks, solve in `litstack/litstack`
